### ISSUE TITLE
M+ Timer no longer shows percentage of current pull

### ISSUE THREAD

**Issue by redcatelf** [Tomslack/ManbabyDungeonTools#89]
As of today, the [M+ Timer](https://wago.io/M+Timer) WeakAura no longer shows the percentage of the current pull, as in [this screenshot](https://media.wago.io/screenshots/zkhTYrEsG/5fa37c7d69a32526cb8c2cc2.png) (+4.62%). Glancing at the code I think the WeakAura uses the global MDT variable, and then `MDT:GetEnemyForces`. Did something change that broke it?

**Comment by srenauld** [comment]
Namespaced it to `DungeonTools` to make sure either could be run, together if needed.

I will add a fallback check when an instance is entered to repopulate the `MDT` global object if it still does not exist (as in, if any other addon is not enabled). In the meantime, you can edit it to use `DungeonTools:GetEnemyForces` - exactly equal in signature.

**Comment by srenauld** [comment]
I've just pushed 1.1.12, it should be up on wowup in a second and in curseforge in a few minutes. This should solve this issue.

**Comment by fjavifabre** [comment]
I have upgraded to the latest version and this problem still occurs to me.

**Comment by srenauld** [comment]
Checked further - the `MDT` reference is in aura init. As a result, adding this on game load would indeed cause problems.

For now, I guess we can live with some namespace clashes; I'll temporarily make the addon also export on `MDT` on boot instead of 1s after, which should fix this, but mean we're back to having either MDT or dungeontools on.

Really hoping to get a reply re: common interface sometime soon.

**Comment by Ilendur** [comment]
Isn't it possible to put MDT in the the OptionalDeps of the TOC, then check whether it's loaded when DungeonTools loads?

**Comment by srenauld** [comment]
@Ilendur That's actually a really good solution! I did not think of that.

**Comment by LordDeimos666** [comment]
Same here, all wa that use MDT as % prevision is broken right now

**Comment by srenauld** [comment]
Try updating to 1.1.13 and let me know if that fixed it; I've done exactly what @Ilendur suggested and then checked on add-on start if `MDT` exists. If it doesn't, DungeonTools registers itself on that global as well.

**Comment by LordDeimos666** [comment]
https://wago.io/9TLNEO4Pt/21 used this, can confirm, 1.1.13 works now

**Comment by srenauld** [comment]
Perfect. Back on to the route issue!
